import os

from dotenv import load_dotenv

load_dotenv()


AZURE_WHISPER_KEY = os.getenv("AZURE_WHISPER_KEY")
AZURE_WHISPER_BASE = os.getenv("AZURE_WHISPER_BASE")
AZURE_WHISPER_DEPLOYMENT = os.getenv("AZURE_WHISPER_DEPLOYMENT")
AZURE_WHISPER_VERSION = os.getenv("AZURE_WHISPER_VERSION")
AZURE_WHISPER_MODEL = os.getenv("AZURE_WHISPER_MODEL")

AZURE_LLM_KEY = os.getenv("AZURE_LLM_KEY")
AZURE_LLM_BASE = os.getenv("AZURE_LLM_BASE")
AZURE_LLM_DEPLOYMENT = os.getenv("AZURE_LLM_DEPLOYMENT")
AZURE_LLM_VERSION = os.getenv("AZURE_LLM_VERSION")
AZURE_LLM_MODEL = os.getenv("AZURE_LLM_MODEL")
